name: Playwright Tests
on:
  workflow_run:
    workflows: ["Baguni Develop Client CI/CD"]
    types: [completed]
  workflow_dispatch:

jobs:
  run-tests:
    name: Run Playwright Tests (Staging)
    environment: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./techpick
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Create .env.development File
        run: |
          touch .env.development
          echo "TEST_BASE_URL=${{ secrets.TEST_BASE_URL }}" >> .env.development

      - name: Enable Corepack
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn

      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps

      - name: Run Playwright tests
        run: yarn playwright test

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: techpick/playwright-report/
          retention-days: 10
      
      - name: SLACK Webhook Notification
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.E2E_SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "*GitHub Action build result*: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
